<?php

namespace AppBundle\Repository;

/**
 * ParentCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
