<?php

namespace AppBundle\Repository;

/**
 * userOrderByCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOrderByCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
