<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLike($input)
    {
        $input = "%".$input ."%";
        $qb = $this->createQueryBuilder('u')
            ->select('u.id,u.firstname,u.lastname')
            ->where('u.firstname LIKE :firstname')
                ->setParameter('firstname', $input)
            ->orWhere('u.lastname LIKE :lastname')
                ->setParameter('lastname',$input)
            ->getQuery();
        return $qb->getResult();
    }
}
